english_word_dict = {
    # Window, menus, shared
    "application_name": "APITestka",
    "menu_language": "Language",
    "menu_language_english": "English",
    "menu_language_traditional_chinese": "Traditional Chinese",
    "menu_language_simplified_chinese": "Simplified Chinese",
    "menu_language_japanese": "Japanese",
    "menu_theme": "Theme",
    "menu_theme_system": "Follow system",
    "menu_theme_light": "Light",
    "menu_theme_dark": "Dark",
    "ready": "Ready",
    "console": "Console",
    "clear": "Clear",
    "error": "Error",
    "browse": "Browse…",
    "refresh": "Refresh",
    "written": "Wrote {path}",
    # Sidebar
    "page_request": "Request",
    "page_environments": "Environments",
    "page_executor": "Executor",
    "page_records": "Records & Reports",
    "page_mock": "Mock Servers",
    "page_contracts": "Contracts",
    "page_openapi": "OpenAPI",
    "page_load": "Load Test",
    "page_trends": "Trends",
    "page_tools": "Tools",
    # Request
    "url_placeholder": "https://api.example.com/items or {{base}}/items",
    "backend_requests": "requests",
    "backend_httpx": "httpx",
    "backend_httpx_async": "httpx (async)",
    "send": "Send",
    "sending": "Sending…",
    "copy_as_action": "Copy as action",
    "copied_action": "Copied the request as an AT_test_api_method action",
    "history": "History",
    "params": "Params",
    "headers": "Headers",
    "body": "Body",
    "auth": "Auth",
    "options": "Options",
    "body_placeholder": "JSON body, or plain text",
    "timeout": "Timeout (s)",
    "verify_ssl": "Verify TLS certificates",
    "allow_redirects": "Follow redirects",
    "soap": "SOAP",
    "result_check": "Result check (JSON)",
    "no_response": "No response yet",
    "response_body": "Body",
    "response_headers": "Headers",
    "response_meta": "{ms:.0f} ms · {size} bytes",
    "request_failed": "Request failed",
    "no_environment": "No environment",
    "environment_activated": "Environment {name} is active",
    # Environments
    "environments_help": "Variables of the active environment fill {{name}} placeholders in the request URL, "
                         "params, headers and body.",
    "new": "New",
    "save": "Save",
    "delete": "Delete",
    "import": "Import",
    "export": "Export",
    "activate": "Activate",
    "environment_name": "Environment name",
    "environment_must_be_object": "an environment is a JSON object of names and values",
    "saved": "Saved {name}",
    # Executor
    "executor_help": "Run APITestka action JSON: [[\"AT_command\", {keyword arguments}], ...].",
    "run": "Run",
    "run_from_disk": "Run from disk",
    "action_file": "Action file",
    "action_folder": "Action folder",
    "run_file": "Run file",
    "run_folder": "Run folder",
    "no_json_files": "No JSON files in that folder",
    # Records & Reports
    "records_help": "Every request the GUI, the executor or a script sends is recorded here until cleared.",
    "clear_records": "Clear records",
    "records_count": "{success} succeeded · {error} failed",
    "column_method": "Method",
    "column_url": "URL",
    "column_status": "Status",
    "column_time_ms": "Time (ms)",
    "no_failures": "No failures",
    "reports": "Reports",
    "report_name": "Report name",
    "records_cleared": "Test records cleared",
    "report_written": "{kind} report written: {name}",
    # Mock servers
    "mock_help": "Serve HTTP routes locally; a mock config file adds WebSocket and gRPC endpoints "
                 "(the same file as `apitestka mock --config`).",
    "http_mock": "Mock server",
    "host": "Host",
    "port": "Port",
    "mock_config_file": "Mock config (optional)",
    "status": "Status",
    "mock_stopped": "Stopped",
    "mock_running": "Running on {host}:{port}",
    "mock_listening": "HTTP mock listening on {host}:{port}",
    "start": "Start",
    "stop_protocol_mocks": "Stop WebSocket and gRPC",
    "protocol_mocks_stopped": "WebSocket and gRPC mocks stopped",
    # Contracts
    "contracts_help": "Record a Pact v2 consumer contract from the test record, replay it against a running "
                      "provider, or check it against the provider's OpenAPI document.",
    "record_contract": "Record a consumer contract",
    "consumer": "Consumer",
    "provider": "Provider",
    "body_rule": "Response bodies",
    "body_rule_type": "Match types",
    "body_rule_equality": "Match exact values",
    "contract_file": "Contract file",
    "record_from_records": "Record from test records",
    "check_contract": "Check a contract",
    "provider_base_url": "Provider base URL",
    "provider_states_url": "Provider states URL (optional)",
    "openapi_file": "OpenAPI document",
    "verify_provider": "Verify provider",
    "compare_openapi": "Compare with OpenAPI",
    # OpenAPI
    "openapi_help": "Infer a document from the test record, check the committed document against it, "
                    "and generate tests for what is untested.",
    "infer_openapi": "Infer from test records",
    "title": "Title",
    "output_file": "Output file",
    "spec_and_tests": "Committed document and tests",
    "min_coverage": "Minimum coverage",
    "missing_actions_file": "Actions output (optional)",
    "ai_backend": "AI backend",
    "check_spec": "Check against tests",
    "generate_tests": "Generate tests",
    # Load test
    "load_help": "Run the requests of an action file (or the test record) as a LoadDensity load test. "
                 "je_load_density must be installed for the chosen interpreter.",
    "load_profile": "Load profile",
    "action_file_or_records": "Action file (empty: test records)",
    "load_user": "User type",
    "users": "Users",
    "spawn_rate": "Spawn rate (/s)",
    "seconds": "Duration (s)",
    "task_mode": "Task order",
    "max_failure_rate": "Max failure rate",
    "max_p95_ms": "Max p95 (ms)",
    "python": "Python",
    "python_placeholder": "Interpreter with je_load_density (empty: this one)",
    "no_limit": "No limit",
    "run_load_test": "Run load test",
    # Trends
    "trends_help": "Store each run's per-endpoint latency and flag endpoints that got clearly slower than "
                   "their history.",
    "trend_database": "Trend database",
    "database": "Database",
    "run_label": "Run label",
    "report_file": "Report file",
    "record_run": "Record this run",
    "check_anomalies": "Check anomalies",
    "open_report": "Open report",
    "column_endpoint": "Endpoint",
    "column_latest": "Latest (ms)",
    "column_baseline": "Baseline (ms)",
    "column_z": "z",
    "run_recorded": "Recorded {endpoints} endpoints (run {run_id})",
    # Tools
    "json_tools": "JSON",
    "input": "Input",
    "output": "Output",
    "read_file": "Read file",
    "write_file": "Write file",
    "format": "Format",
    "xml_tools": "XML",
    "xml_file": "XML file",
    "reformat_in_place": "Reformat in place",
    "create_project": "Create a project",
    "folder": "Folder",
    "project_name": "Project name",
    "create": "Create",
    "project_created": "Project created: {name}",
}
