english_word_dict = {
    # Main
    "application_name": "APITestka",
    # Menu
    "menu_language": "Language",
    "menu_language_english": "English",
    "menu_language_chinese": "Traditional Chinese",
    # Tabs
    "tab_api_request": "API Request",
    "tab_executor": "Executor",
    "tab_reports": "Reports",
    "tab_mock_server": "Mock Server",
    "tab_test_records": "Test Records",
    "tab_tools": "Tools",
    # API Request tab
    "url": "URL:",
    "send": "Send",
    "backend": "Backend:",
    "backend_requests": "requests",
    "backend_httpx": "httpx (sync)",
    "backend_httpx_async": "httpx (async)",
    "param": "Params",
    "headers": "Headers",
    "body": "Body",
    "auth": "Auth",
    "timeout": "Timeout (s):",
    "verify_ssl": "Verify SSL",
    "allow_redirects": "Allow Redirects",
    "soap": "SOAP",
    "result_check": "Result Check (JSON):",
    "result_check_placeholder": '{"status_code": 200}',
    "response_and_log": "Response / Log:",
    "param_placeholder": '{"key": "value"}',
    "headers_placeholder": '{"Content-Type": "application/json"}',
    "body_placeholder": "Request body (JSON or text)",
    "auth_placeholder": '{"username": "user", "password": "pass"}',
    # API Response fields
    "status_code": "Status Code: ",
    "text": "Text: ",
    "content": "Content: ",
    "history": "History: ",
    "encoding": "Encoding: ",
    "cookies": "Cookies: ",
    "elapsed": "Elapsed: ",
    "request_method": "Request Method: ",
    "request_url": "Request URL: ",
    "request_body": "Request Body: ",
    "request_time_sec": "Request Time (s): ",
    "start_time": "Start Time: ",
    "end_time": "End Time: ",
    # HTTP methods
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    "session_get": "Session GET",
    "session_post": "Session POST",
    "session_put": "Session PUT",
    "session_patch": "Session PATCH",
    "session_delete": "Session DELETE",
    "session_head": "Session HEAD",
    "session_options": "Session OPTIONS",
    # Executor tab
    "executor_json_input": "Action JSON:",
    "executor_json_placeholder": '[["AT_test_api_method_httpx", {"http_method": "get", "test_url": "http://httpbin.org/get"}]]',
    "executor_run": "Run Actions",
    "executor_load_file": "Load JSON File",
    "executor_run_file": "Run File",
    "executor_load_dir": "Load Directory",
    "executor_run_dir": "Run All Files",
    "executor_output": "Output:",
    "executor_file_path": "File Path:",
    "executor_dir_path": "Directory Path:",
    # Reports tab
    "report_file_name": "Report File Name:",
    "report_file_name_default": "test_report",
    "report_generate_html": "Generate HTML Report",
    "report_generate_json": "Generate JSON Report",
    "report_generate_xml": "Generate XML Report",
    "report_status": "Report Status:",
    # Mock Server tab
    "mock_host": "Host:",
    "mock_port": "Port:",
    "mock_start": "Start Server",
    "mock_status": "Server Status:",
    "mock_status_stopped": "Stopped",
    "mock_status_running": "Running",
    # Test Records tab
    "records_success": "Success Records:",
    "records_error": "Error Records:",
    "records_clean": "Clean All Records",
    "records_refresh": "Refresh",
    "records_count": "Success: {success} | Error: {error}",
    # Tools tab
    "tools_json_reformat": "JSON Reformat",
    "tools_json_input": "JSON Input:",
    "tools_json_output": "Formatted Output:",
    "tools_json_format_btn": "Format",
    "tools_json_read": "Read JSON File",
    "tools_json_write": "Write JSON File",
    "tools_xml_reformat": "XML Reformat",
    "tools_xml_input": "XML File Path:",
    "tools_xml_reformat_btn": "Reformat XML",
    "tools_create_project": "Create Project",
    "tools_project_path": "Project Path:",
    "tools_project_name": "Project Name:",
    "tools_project_create_btn": "Create",
    "tools_project_name_default": "APITestka",
    # Common
    "browse": "Browse...",
    "clear": "Clear",
    "success": "Success",
    "error": "Error",
}
