japanese_word_dict = {
    # ウィンドウ、メニュー、共通
    "application_name": "APITestka",
    "menu_language": "言語",
    "menu_language_english": "English",
    "menu_language_traditional_chinese": "繁體中文",
    "menu_language_simplified_chinese": "简体中文",
    "menu_language_japanese": "日本語",
    "menu_theme": "テーマ",
    "menu_theme_system": "システムに合わせる",
    "menu_theme_light": "ライト",
    "menu_theme_dark": "ダーク",
    "ready": "準備完了",
    "console": "コンソール",
    "clear": "クリア",
    "error": "エラー",
    "browse": "参照…",
    "refresh": "更新",
    "written": "{path} に書き出しました",
    # サイドバー
    "page_request": "リクエスト",
    "page_environments": "環境",
    "page_executor": "エグゼキューター",
    "page_records": "記録とレポート",
    "page_mock": "モックサーバー",
    "page_contracts": "コントラクト",
    "page_openapi": "OpenAPI",
    "page_load": "負荷テスト",
    "page_trends": "トレンド",
    "page_tools": "ツール",
    # リクエスト
    "url_placeholder": "https://api.example.com/items または {{base}}/items",
    "backend_requests": "requests",
    "backend_httpx": "httpx",
    "backend_httpx_async": "httpx（非同期）",
    "send": "送信",
    "sending": "送信中…",
    "copy_as_action": "action としてコピー",
    "copied_action": "リクエストを AT_test_api_method action としてコピーしました",
    "history": "履歴",
    "params": "パラメーター",
    "headers": "ヘッダー",
    "body": "ボディ",
    "auth": "認証",
    "options": "オプション",
    "body_placeholder": "JSON ボディ、またはプレーンテキスト",
    "timeout": "タイムアウト（秒）",
    "verify_ssl": "TLS 証明書を検証",
    "allow_redirects": "リダイレクトに従う",
    "soap": "SOAP",
    "result_check": "結果チェック（JSON）",
    "no_response": "まだレスポンスがありません",
    "response_body": "ボディ",
    "response_headers": "ヘッダー",
    "response_meta": "{ms:.0f} ミリ秒 · {size} バイト",
    "request_failed": "リクエスト失敗",
    "no_environment": "環境なし",
    "environment_activated": "環境 {name} を有効にしました",
    # 環境
    "environments_help": "有効な環境の変数が、リクエストの URL、パラメーター、ヘッダー、ボディの {{name}} "
                         "プレースホルダーに入ります。",
    "new": "新規",
    "save": "保存",
    "delete": "削除",
    "import": "インポート",
    "export": "エクスポート",
    "activate": "有効にする",
    "environment_name": "環境名",
    "environment_must_be_object": "環境は名前と値からなる JSON オブジェクトです",
    "saved": "{name} を保存しました",
    # エグゼキューター
    "executor_help": "APITestka の action JSON を実行します：[[\"AT_command\", {キーワード引数}], ...]。",
    "run": "実行",
    "run_from_disk": "ディスクから実行",
    "action_file": "Action ファイル",
    "action_folder": "Action フォルダー",
    "run_file": "ファイルを実行",
    "run_folder": "フォルダーを実行",
    "no_json_files": "そのフォルダーに JSON ファイルがありません",
    # 記録とレポート
    "records_help": "GUI、エグゼキューター、スクリプトが送ったすべてのリクエストは、クリアするまでここに記録されます。",
    "clear_records": "記録をクリア",
    "records_count": "成功 {success} 件 · 失敗 {error} 件",
    "column_method": "メソッド",
    "column_url": "URL",
    "column_status": "ステータス",
    "column_time_ms": "時間（ミリ秒）",
    "no_failures": "失敗はありません",
    "reports": "レポート",
    "report_name": "レポート名",
    "records_cleared": "テスト記録をクリアしました",
    "report_written": "{kind} レポートを書き出しました：{name}",
    # モックサーバー
    "mock_help": "ローカルで HTTP ルートを提供します。モック設定ファイルで WebSocket と gRPC のエンドポイントも追加で"
                 "きます（`apitestka mock --config` と同じファイル）。",
    "http_mock": "モックサーバー",
    "host": "ホスト",
    "port": "ポート",
    "mock_config_file": "モック設定（任意）",
    "status": "ステータス",
    "mock_stopped": "停止中",
    "mock_running": "実行中：{host}:{port}",
    "mock_listening": "HTTP モックが {host}:{port} で待ち受けています",
    "start": "開始",
    "stop_protocol_mocks": "WebSocket と gRPC を停止",
    "protocol_mocks_stopped": "WebSocket と gRPC のモックを停止しました",
    # コントラクト
    "contracts_help": "テスト記録から Pact v2 のコンシューマーコントラクトを作り、稼働中のプロバイダーで再生するか、"
                      "プロバイダーの OpenAPI ドキュメントと照合します。",
    "record_contract": "コンシューマーコントラクトを作成",
    "consumer": "コンシューマー",
    "provider": "プロバイダー",
    "body_rule": "レスポンスボディ",
    "body_rule_type": "型を照合",
    "body_rule_equality": "値を完全一致で照合",
    "contract_file": "コントラクトファイル",
    "record_from_records": "テスト記録から作成",
    "check_contract": "コントラクトを確認",
    "provider_base_url": "プロバイダーのベース URL",
    "provider_states_url": "プロバイダー状態 URL（任意）",
    "openapi_file": "OpenAPI ドキュメント",
    "verify_provider": "プロバイダーを検証",
    "compare_openapi": "OpenAPI と照合",
    # OpenAPI
    "openapi_help": "テスト記録からドキュメントを推論し、コミット済みのドキュメントと照合し、テストされていない部分の"
                    "テストを生成します。",
    "infer_openapi": "テスト記録から推論",
    "title": "タイトル",
    "output_file": "出力ファイル",
    "spec_and_tests": "コミット済みドキュメントとテスト",
    "min_coverage": "最低カバレッジ",
    "missing_actions_file": "Action の出力先（任意）",
    "ai_backend": "AI バックエンド",
    "check_spec": "テストと照合",
    "generate_tests": "テストを生成",
    # 負荷テスト
    "load_help": "action ファイル（またはテスト記録）のリクエストを LoadDensity の負荷テストとして実行します。"
                 "選んだインタープリターに je_load_density が必要です。",
    "load_profile": "負荷プロファイル",
    "action_file_or_records": "Action ファイル（空欄：テスト記録）",
    "load_user": "ユーザー種別",
    "users": "ユーザー数",
    "spawn_rate": "起動レート（/秒）",
    "seconds": "時間（秒）",
    "task_mode": "Task の順序",
    "max_failure_rate": "最大失敗率",
    "max_p95_ms": "最大 p95（ミリ秒）",
    "python": "Python",
    "python_placeholder": "je_load_density が入ったインタープリター（空欄：このインタープリター）",
    "no_limit": "制限なし",
    "run_load_test": "負荷テストを実行",
    # トレンド
    "trends_help": "実行ごとにエンドポイント別のレイテンシーを記録し、履歴より明らかに遅くなったエンドポイントを示し"
                   "ます。",
    "trend_database": "トレンドデータベース",
    "database": "データベース",
    "run_label": "実行ラベル",
    "report_file": "レポートファイル",
    "record_run": "この実行を記録",
    "check_anomalies": "異常を確認",
    "open_report": "レポートを開く",
    "column_endpoint": "エンドポイント",
    "column_latest": "最新（ミリ秒）",
    "column_baseline": "基準（ミリ秒）",
    "column_z": "z",
    "run_recorded": "{endpoints} 個のエンドポイントを記録しました（実行 {run_id}）",
    # ツール
    "json_tools": "JSON",
    "input": "入力",
    "output": "出力",
    "read_file": "ファイルを読み込む",
    "write_file": "ファイルに書き出す",
    "format": "整形",
    "xml_tools": "XML",
    "xml_file": "XML ファイル",
    "reformat_in_place": "その場で整形",
    "create_project": "プロジェクトを作成",
    "folder": "フォルダー",
    "project_name": "プロジェクト名",
    "create": "作成",
    "project_created": "プロジェクトを作成しました：{name}",
}
