japanese_word_dict = {
    # Main
    "application_name": "APITestka",
    # Menu
    "menu_language": "言語",
    "menu_language_english": "英語",
    "menu_language_chinese": "繁体字中国語",
    "menu_language_japanese": "日本語",
    "menu_language_simplified_chinese": "簡体字中国語",
    # Tabs
    "tab_api_request": "APIリクエスト",
    "tab_executor": "エグゼキュータ",
    "tab_reports": "レポート",
    "tab_mock_server": "モックサーバー",
    "tab_test_records": "テスト記録",
    "tab_tools": "ツール",
    # API Request tab
    "url": "URL：",
    "send": "送信",
    "backend": "バックエンド：",
    "backend_requests": "requests",
    "backend_httpx": "httpx (同期)",
    "backend_httpx_async": "httpx (非同期)",
    "param": "パラメータ",
    "headers": "ヘッダー",
    "body": "本文",
    "auth": "認証",
    "timeout": "タイムアウト (秒)：",
    "verify_ssl": "SSL を検証",
    "allow_redirects": "リダイレクトを許可",
    "soap": "SOAP",
    "result_check": "結果チェック (JSON)：",
    "result_check_placeholder": '{"status_code": 200}',
    "response_and_log": "レスポンス / ログ：",
    "param_placeholder": '{"key": "value"}',
    "headers_placeholder": '{"Content-Type": "application/json"}',
    "body_placeholder": "リクエスト本文 (JSON またはテキスト)",
    "auth_placeholder": '{"username": "user", "password": "pass"}',
    # API Response fields
    "status_code": "ステータスコード：",
    "text": "テキスト：",
    "content": "コンテンツ：",
    "history": "履歴：",
    "encoding": "エンコーディング：",
    "cookies": "クッキー：",
    "elapsed": "経過時間：",
    "request_method": "リクエストメソッド：",
    "request_url": "リクエスト URL：",
    "request_body": "リクエスト本文：",
    "request_time_sec": "リクエスト時間 (秒)：",
    "start_time": "開始時刻：",
    "end_time": "終了時刻：",
    # HTTP methods
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    "session_get": "セッション GET",
    "session_post": "セッション POST",
    "session_put": "セッション PUT",
    "session_patch": "セッション PATCH",
    "session_delete": "セッション DELETE",
    "session_head": "セッション HEAD",
    "session_options": "セッション OPTIONS",
    # Executor tab
    "executor_json_input": "アクション JSON：",
    "executor_json_placeholder": '[["AT_test_api_method_httpx", {"http_method": "get", "test_url": "https://httpbin.org/get"}]]',
    "executor_run": "アクションを実行",
    "executor_load_file": "JSON ファイルを読み込み",
    "executor_run_file": "ファイルを実行",
    "executor_load_dir": "ディレクトリを読み込み",
    "executor_run_dir": "全ファイルを実行",
    "executor_output": "出力：",
    "executor_file_path": "ファイルパス：",
    "executor_dir_path": "ディレクトリパス：",
    # Reports tab
    "report_file_name": "レポートファイル名：",
    "report_file_name_default": "test_report",
    "report_generate_html": "HTML レポート生成",
    "report_generate_json": "JSON レポート生成",
    "report_generate_xml": "XML レポート生成",
    "report_status": "レポート状態：",
    # Mock Server tab
    "mock_host": "ホスト：",
    "mock_port": "ポート：",
    "mock_start": "サーバー起動",
    "mock_status": "サーバー状態：",
    "mock_status_stopped": "停止中",
    "mock_status_running": "実行中",
    # Test Records tab
    "records_success": "成功記録：",
    "records_error": "エラー記録：",
    "records_clean": "全記録をクリア",
    "records_refresh": "更新",
    "records_count": "成功：{success} | エラー：{error}",
    # Tools tab
    "tools_json_reformat": "JSON 整形",
    "tools_json_input": "JSON 入力：",
    "tools_json_output": "整形後の出力：",
    "tools_json_format_btn": "整形",
    "tools_json_read": "JSON ファイル読み込み",
    "tools_json_write": "JSON ファイル書き込み",
    "tools_xml_reformat": "XML 整形",
    "tools_xml_input": "XML ファイルパス：",
    "tools_xml_reformat_btn": "XML を整形",
    "tools_create_project": "プロジェクト作成",
    "tools_project_path": "プロジェクトパス：",
    "tools_project_name": "プロジェクト名：",
    "tools_project_create_btn": "作成",
    "tools_project_name_default": "APITestka",
    # Common
    "browse": "参照...",
    "clear": "クリア",
    "success": "成功",
    "error": "エラー",
}
