simplified_chinese_word_dict = {
    # Main
    "application_name": "APITestka",
    # Menu
    "menu_language": "语言",
    "menu_language_english": "英文",
    "menu_language_chinese": "繁体中文",
    "menu_language_japanese": "日文",
    "menu_language_simplified_chinese": "简体中文",
    # Tabs
    "tab_api_request": "API 请求",
    "tab_executor": "执行器",
    "tab_reports": "报告",
    "tab_mock_server": "模拟服务器",
    "tab_test_records": "测试记录",
    "tab_tools": "工具",
    # API Request tab
    "url": "网址：",
    "send": "发送",
    "backend": "后端：",
    "backend_requests": "requests",
    "backend_httpx": "httpx (同步)",
    "backend_httpx_async": "httpx (异步)",
    "param": "参数",
    "headers": "标头",
    "body": "主体",
    "auth": "认证",
    "timeout": "超时 (秒)：",
    "verify_ssl": "验证 SSL",
    "allow_redirects": "允许重定向",
    "soap": "SOAP",
    "result_check": "结果检查 (JSON)：",
    "result_check_placeholder": '{"status_code": 200}',
    "response_and_log": "响应 / 日志：",
    "param_placeholder": '{"key": "value"}',
    "headers_placeholder": '{"Content-Type": "application/json"}',
    "body_placeholder": "请求主体 (JSON 或文本)",
    "auth_placeholder": '{"username": "user", "password": "pass"}',
    # API Response fields
    "status_code": "状态码：",
    "text": "文本：",
    "content": "内容：",
    "history": "历史：",
    "encoding": "编码：",
    "cookies": "Cookies：",
    "elapsed": "耗时：",
    "request_method": "请求方法：",
    "request_url": "请求网址：",
    "request_body": "请求主体：",
    "request_time_sec": "请求时间 (秒)：",
    "start_time": "开始时间：",
    "end_time": "结束时间：",
    # HTTP methods
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    "session_get": "会话 GET",
    "session_post": "会话 POST",
    "session_put": "会话 PUT",
    "session_patch": "会话 PATCH",
    "session_delete": "会话 DELETE",
    "session_head": "会话 HEAD",
    "session_options": "会话 OPTIONS",
    # Executor tab
    "executor_json_input": "动作 JSON：",
    "executor_json_placeholder": '[["AT_test_api_method_httpx", {"http_method": "get", "test_url": "https://httpbin.org/get"}]]',
    "executor_run": "执行动作",
    "executor_load_file": "加载 JSON 文件",
    "executor_run_file": "运行文件",
    "executor_load_dir": "加载目录",
    "executor_run_dir": "运行所有文件",
    "executor_output": "输出：",
    "executor_file_path": "文件路径：",
    "executor_dir_path": "目录路径：",
    # Reports tab
    "report_file_name": "报告文件名：",
    "report_file_name_default": "test_report",
    "report_generate_html": "生成 HTML 报告",
    "report_generate_json": "生成 JSON 报告",
    "report_generate_xml": "生成 XML 报告",
    "report_status": "报告状态：",
    # Mock Server tab
    "mock_host": "主机：",
    "mock_port": "端口：",
    "mock_start": "启动服务器",
    "mock_status": "服务器状态：",
    "mock_status_stopped": "已停止",
    "mock_status_running": "运行中",
    # Test Records tab
    "records_success": "成功记录：",
    "records_error": "错误记录：",
    "records_clean": "清除所有记录",
    "records_refresh": "刷新",
    "records_count": "成功：{success} | 错误：{error}",
    # Tools tab
    "tools_json_reformat": "JSON 重排",
    "tools_json_input": "JSON 输入：",
    "tools_json_output": "格式化输出：",
    "tools_json_format_btn": "格式化",
    "tools_json_read": "读取 JSON 文件",
    "tools_json_write": "写入 JSON 文件",
    "tools_xml_reformat": "XML 重排",
    "tools_xml_input": "XML 文件路径：",
    "tools_xml_reformat_btn": "重排 XML",
    "tools_create_project": "创建项目",
    "tools_project_path": "项目路径：",
    "tools_project_name": "项目名称：",
    "tools_project_create_btn": "创建",
    "tools_project_name_default": "APITestka",
    # Common
    "browse": "浏览...",
    "clear": "清除",
    "success": "成功",
    "error": "错误",
}
