simplified_chinese_word_dict = {
    # 窗口、菜单、共用
    "application_name": "APITestka",
    "menu_language": "语言",
    "menu_language_english": "English",
    "menu_language_traditional_chinese": "繁體中文",
    "menu_language_simplified_chinese": "简体中文",
    "menu_language_japanese": "日本語",
    "menu_theme": "主题",
    "menu_theme_system": "跟随系统",
    "menu_theme_light": "浅色",
    "menu_theme_dark": "深色",
    "ready": "就绪",
    "console": "控制台",
    "clear": "清除",
    "error": "错误",
    "browse": "浏览…",
    "refresh": "刷新",
    "written": "已写入 {path}",
    # 侧边栏
    "page_request": "请求",
    "page_environments": "环境",
    "page_executor": "执行器",
    "page_records": "记录与报告",
    "page_mock": "模拟服务器",
    "page_contracts": "契约",
    "page_openapi": "OpenAPI",
    "page_load": "负载测试",
    "page_trends": "趋势",
    "page_tools": "工具",
    # 请求
    "url_placeholder": "https://api.example.com/items 或 {{base}}/items",
    "backend_requests": "requests",
    "backend_httpx": "httpx",
    "backend_httpx_async": "httpx（异步）",
    "send": "发送",
    "sending": "发送中…",
    "copy_as_action": "复制为 action",
    "copied_action": "已把请求复制为 AT_test_api_method action",
    "history": "历史记录",
    "params": "参数",
    "headers": "请求头",
    "body": "请求体",
    "auth": "认证",
    "options": "选项",
    "body_placeholder": "JSON 请求体，或纯文本",
    "timeout": "超时（秒）",
    "verify_ssl": "验证 TLS 证书",
    "allow_redirects": "跟随重定向",
    "soap": "SOAP",
    "result_check": "结果检查（JSON）",
    "no_response": "尚无响应",
    "response_body": "响应体",
    "response_headers": "响应头",
    "response_meta": "{ms:.0f} 毫秒 · {size} 字节",
    "request_failed": "请求失败",
    "no_environment": "不使用环境",
    "environment_activated": "已启用环境 {name}",
    # 环境
    "environments_help": "启用中环境的变量会填入请求 URL、参数、请求头与请求体里的 {{name}} 占位符。",
    "new": "新建",
    "save": "保存",
    "delete": "删除",
    "import": "导入",
    "export": "导出",
    "activate": "启用",
    "environment_name": "环境名称",
    "environment_must_be_object": "环境必须是由名称与值组成的 JSON 对象",
    "saved": "已保存 {name}",
    # 执行器
    "executor_help": "执行 APITestka action JSON：[[\"AT_command\", {关键字参数}], ...]。",
    "run": "运行",
    "run_from_disk": "从磁盘运行",
    "action_file": "Action 文件",
    "action_folder": "Action 文件夹",
    "run_file": "运行文件",
    "run_folder": "运行文件夹",
    "no_json_files": "该文件夹里没有 JSON 文件",
    # 记录与报告
    "records_help": "GUI、执行器或脚本发出的每个请求都会记录在这里，直到清除为止。",
    "clear_records": "清除记录",
    "records_count": "成功 {success} 条 · 失败 {error} 条",
    "column_method": "方法",
    "column_url": "URL",
    "column_status": "状态",
    "column_time_ms": "耗时（毫秒）",
    "no_failures": "没有失败",
    "reports": "报告",
    "report_name": "报告名称",
    "records_cleared": "已清除测试记录",
    "report_written": "已生成 {kind} 报告：{name}",
    # 模拟服务器
    "mock_help": "在本机提供 HTTP 路由；模拟配置文件可再加上 WebSocket 与 gRPC 端点（与 `apitestka mock --config` "
                 "使用同一个文件）。",
    "http_mock": "模拟服务器",
    "host": "主机",
    "port": "端口",
    "mock_config_file": "模拟配置文件（可选）",
    "status": "状态",
    "mock_stopped": "已停止",
    "mock_running": "运行中：{host}:{port}",
    "mock_listening": "HTTP 模拟服务器在 {host}:{port} 监听",
    "start": "启动",
    "stop_protocol_mocks": "停止 WebSocket 与 gRPC",
    "protocol_mocks_stopped": "已停止 WebSocket 与 gRPC 模拟",
    # 契约
    "contracts_help": "从测试记录生成 Pact v2 消费者契约、把它重放到运行中的提供端，或与提供端的 OpenAPI 文档比较。",
    "record_contract": "生成消费者契约",
    "consumer": "消费端",
    "provider": "提供端",
    "body_rule": "响应体",
    "body_rule_type": "匹配类型",
    "body_rule_equality": "匹配确切的值",
    "contract_file": "契约文件",
    "record_from_records": "从测试记录生成",
    "check_contract": "检查契约",
    "provider_base_url": "提供端地址",
    "provider_states_url": "提供端状态地址（可选）",
    "openapi_file": "OpenAPI 文档",
    "verify_provider": "验证提供端",
    "compare_openapi": "与 OpenAPI 比较",
    # OpenAPI
    "openapi_help": "从测试记录推导出文档、把已提交的文档与它比较，并为没测到的部分生成测试。",
    "infer_openapi": "从测试记录推导",
    "title": "标题",
    "output_file": "输出文件",
    "spec_and_tests": "已提交的文档与测试",
    "min_coverage": "最低覆盖率",
    "missing_actions_file": "Action 输出（可选）",
    "ai_backend": "AI 后端",
    "check_spec": "与测试比较",
    "generate_tests": "生成测试",
    # 负载测试
    "load_help": "把 action 文件（或测试记录）里的请求运行为 LoadDensity 负载测试。所选的解释器必须装有 je_load_densi"
                 "ty。",
    "load_profile": "负载设置",
    "action_file_or_records": "Action 文件（留空：测试记录）",
    "load_user": "用户类型",
    "users": "用户数",
    "spawn_rate": "每秒生成数",
    "seconds": "持续时间（秒）",
    "task_mode": "Task 顺序",
    "max_failure_rate": "最高失败率",
    "max_p95_ms": "最高 p95（毫秒）",
    "python": "Python",
    "python_placeholder": "装有 je_load_density 的解释器（留空：当前这个）",
    "no_limit": "不限制",
    "run_load_test": "运行负载测试",
    # 趋势
    "trends_help": "记录每次运行各端点的延迟，并标出比历史明显变慢的端点。",
    "trend_database": "趋势数据库",
    "database": "数据库",
    "run_label": "运行标签",
    "report_file": "报告文件",
    "record_run": "记录这次运行",
    "check_anomalies": "检查异常",
    "open_report": "打开报告",
    "column_endpoint": "端点",
    "column_latest": "最新（毫秒）",
    "column_baseline": "基准（毫秒）",
    "column_z": "z",
    "run_recorded": "已记录 {endpoints} 个端点（运行 {run_id}）",
    # 工具
    "json_tools": "JSON",
    "input": "输入",
    "output": "输出",
    "read_file": "读取文件",
    "write_file": "写入文件",
    "format": "格式化",
    "xml_tools": "XML",
    "xml_file": "XML 文件",
    "reformat_in_place": "直接重新格式化",
    "create_project": "创建项目",
    "folder": "文件夹",
    "project_name": "项目名称",
    "create": "创建",
    "project_created": "已创建项目：{name}",
}
