traditional_chinese_word_dict = {
    # 視窗、選單、共用
    "application_name": "APITestka",
    "menu_language": "語言",
    "menu_language_english": "English",
    "menu_language_traditional_chinese": "繁體中文",
    "menu_language_simplified_chinese": "简体中文",
    "menu_language_japanese": "日本語",
    "menu_theme": "主題",
    "menu_theme_system": "跟隨系統",
    "menu_theme_light": "淺色",
    "menu_theme_dark": "深色",
    "ready": "就緒",
    "console": "主控台",
    "clear": "清除",
    "error": "錯誤",
    "browse": "瀏覽…",
    "refresh": "重新整理",
    "written": "已寫入 {path}",
    # 側邊欄
    "page_request": "請求",
    "page_environments": "環境",
    "page_executor": "執行器",
    "page_records": "紀錄與報告",
    "page_mock": "模擬伺服器",
    "page_contracts": "契約",
    "page_openapi": "OpenAPI",
    "page_load": "負載測試",
    "page_trends": "趨勢",
    "page_tools": "工具",
    # 請求
    "url_placeholder": "https://api.example.com/items 或 {{base}}/items",
    "backend_requests": "requests",
    "backend_httpx": "httpx",
    "backend_httpx_async": "httpx（非同步）",
    "send": "送出",
    "sending": "送出中…",
    "copy_as_action": "複製成 action",
    "copied_action": "已把請求複製成 AT_test_api_method action",
    "history": "歷史紀錄",
    "params": "參數",
    "headers": "標頭",
    "body": "內容",
    "auth": "驗證",
    "options": "選項",
    "body_placeholder": "JSON 內容，或純文字",
    "timeout": "逾時（秒）",
    "verify_ssl": "驗證 TLS 憑證",
    "allow_redirects": "跟隨重新導向",
    "soap": "SOAP",
    "result_check": "結果檢查（JSON）",
    "no_response": "尚無回應",
    "response_body": "內容",
    "response_headers": "標頭",
    "response_meta": "{ms:.0f} 毫秒 · {size} 位元組",
    "request_failed": "請求失敗",
    "no_environment": "不使用環境",
    "environment_activated": "已啟用環境 {name}",
    # 環境
    "environments_help": "啟用中環境的變數會填入請求網址、參數、標頭與內容裡的 {{name}} 預留位置。",
    "new": "新增",
    "save": "儲存",
    "delete": "刪除",
    "import": "匯入",
    "export": "匯出",
    "activate": "啟用",
    "environment_name": "環境名稱",
    "environment_must_be_object": "環境必須是由名稱與值組成的 JSON 物件",
    "saved": "已儲存 {name}",
    # 執行器
    "executor_help": "執行 APITestka action JSON：[[\"AT_command\", {關鍵字參數}], ...]。",
    "run": "執行",
    "run_from_disk": "從磁碟執行",
    "action_file": "Action 檔案",
    "action_folder": "Action 資料夾",
    "run_file": "執行檔案",
    "run_folder": "執行資料夾",
    "no_json_files": "該資料夾裡沒有 JSON 檔案",
    # 紀錄與報告
    "records_help": "GUI、執行器或腳本送出的每個請求都會記錄在這裡，直到清除為止。",
    "clear_records": "清除紀錄",
    "records_count": "成功 {success} 筆 · 失敗 {error} 筆",
    "column_method": "方法",
    "column_url": "網址",
    "column_status": "狀態",
    "column_time_ms": "時間（毫秒）",
    "no_failures": "沒有失敗",
    "reports": "報告",
    "report_name": "報告名稱",
    "records_cleared": "已清除測試紀錄",
    "report_written": "已寫出 {kind} 報告：{name}",
    # 模擬伺服器
    "mock_help": "在本機提供 HTTP 路由；模擬設定檔可再加上 WebSocket 與 gRPC 端點（與 `apitestka mock --config` "
                 "用同一個檔案）。",
    "http_mock": "模擬伺服器",
    "host": "主機",
    "port": "埠號",
    "mock_config_file": "模擬設定檔（可省略）",
    "status": "狀態",
    "mock_stopped": "已停止",
    "mock_running": "執行中：{host}:{port}",
    "mock_listening": "HTTP 模擬伺服器在 {host}:{port} 監聽",
    "start": "啟動",
    "stop_protocol_mocks": "停止 WebSocket 與 gRPC",
    "protocol_mocks_stopped": "已停止 WebSocket 與 gRPC 模擬",
    # 契約
    "contracts_help": "從測試紀錄產生 Pact v2 消費者契約、把它重播到執行中的提供端，或和提供端的 OpenAPI 文件比對。",
    "record_contract": "產生消費者契約",
    "consumer": "消費端",
    "provider": "提供端",
    "body_rule": "回應內容",
    "body_rule_type": "比對型別",
    "body_rule_equality": "比對確切的值",
    "contract_file": "契約檔案",
    "record_from_records": "從測試紀錄產生",
    "check_contract": "檢查契約",
    "provider_base_url": "提供端網址",
    "provider_states_url": "提供端狀態網址（可省略）",
    "openapi_file": "OpenAPI 文件",
    "verify_provider": "驗證提供端",
    "compare_openapi": "與 OpenAPI 比對",
    # OpenAPI
    "openapi_help": "從測試紀錄推導出文件、拿已提交的文件和它比對，並替沒測到的部分產生測試。",
    "infer_openapi": "從測試紀錄推導",
    "title": "標題",
    "output_file": "輸出檔案",
    "spec_and_tests": "已提交的文件與測試",
    "min_coverage": "最低覆蓋率",
    "missing_actions_file": "Action 輸出（可省略）",
    "ai_backend": "AI 後端",
    "check_spec": "和測試比對",
    "generate_tests": "產生測試",
    # 負載測試
    "load_help": "把 action 檔（或測試紀錄）裡的請求跑成 LoadDensity 負載測試。所選的直譯器必須裝有 je_load_density。",
    "load_profile": "負載設定",
    "action_file_or_records": "Action 檔案（空白：測試紀錄）",
    "load_user": "使用者類型",
    "users": "使用者數",
    "spawn_rate": "每秒產生數",
    "seconds": "持續時間（秒）",
    "task_mode": "Task 順序",
    "max_failure_rate": "最高失敗率",
    "max_p95_ms": "最高 p95（毫秒）",
    "python": "Python",
    "python_placeholder": "裝有 je_load_density 的直譯器（空白：目前這個）",
    "no_limit": "不限制",
    "run_load_test": "執行負載測試",
    # 趨勢
    "trends_help": "記錄每次執行各端點的延遲，並標出比歷史明顯變慢的端點。",
    "trend_database": "趨勢資料庫",
    "database": "資料庫",
    "run_label": "執行標籤",
    "report_file": "報告檔案",
    "record_run": "記錄這次執行",
    "check_anomalies": "檢查異常",
    "open_report": "開啟報告",
    "column_endpoint": "端點",
    "column_latest": "最新（毫秒）",
    "column_baseline": "基準（毫秒）",
    "column_z": "z",
    "run_recorded": "已記錄 {endpoints} 個端點（執行 {run_id}）",
    # 工具
    "json_tools": "JSON",
    "input": "輸入",
    "output": "輸出",
    "read_file": "讀取檔案",
    "write_file": "寫入檔案",
    "format": "排版",
    "xml_tools": "XML",
    "xml_file": "XML 檔案",
    "reformat_in_place": "直接重新排版",
    "create_project": "建立專案",
    "folder": "資料夾",
    "project_name": "專案名稱",
    "create": "建立",
    "project_created": "已建立專案：{name}",
}
