traditional_chinese_word_dict = {
    # Main
    "application_name": "APITestka",
    # Menu
    "menu_language": "語言",
    "menu_language_english": "English",
    "menu_language_chinese": "繁體中文",
    # Tabs
    "tab_api_request": "API 請求",
    "tab_executor": "執行器",
    "tab_reports": "報告",
    "tab_mock_server": "模擬伺服器",
    "tab_test_records": "測試紀錄",
    "tab_tools": "工具",
    # API Request tab
    "url": "URL:",
    "send": "傳送",
    "backend": "後端:",
    "backend_requests": "requests",
    "backend_httpx": "httpx (同步)",
    "backend_httpx_async": "httpx (非同步)",
    "param": "參數",
    "headers": "標頭",
    "body": "內容",
    "auth": "認證",
    "timeout": "逾時 (秒):",
    "verify_ssl": "驗證 SSL",
    "allow_redirects": "允許重導",
    "soap": "SOAP",
    "result_check": "結果檢查 (JSON):",
    "result_check_placeholder": '{"status_code": 200}',
    "response_and_log": "回應 / 日誌:",
    "param_placeholder": '{"key": "value"}',
    "headers_placeholder": '{"Content-Type": "application/json"}',
    "body_placeholder": "請求內容 (JSON 或文字)",
    "auth_placeholder": '{"username": "user", "password": "pass"}',
    # API Response fields
    "status_code": "狀態碼: ",
    "text": "文字: ",
    "content": "內容: ",
    "history": "歷史: ",
    "encoding": "編碼: ",
    "cookies": "Cookies: ",
    "elapsed": "耗時: ",
    "request_method": "請求方法: ",
    "request_url": "請求 URL: ",
    "request_body": "請求內容: ",
    "request_time_sec": "請求時間 (秒): ",
    "start_time": "開始時間: ",
    "end_time": "結束時間: ",
    # HTTP methods
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    "session_get": "Session GET",
    "session_post": "Session POST",
    "session_put": "Session PUT",
    "session_patch": "Session PATCH",
    "session_delete": "Session DELETE",
    "session_head": "Session HEAD",
    "session_options": "Session OPTIONS",
    # Executor tab
    "executor_json_input": "動作 JSON:",
    "executor_json_placeholder": '[["AT_test_api_method_httpx", {"http_method": "get", "test_url": "https://httpbin.org/get"}]]',
    "executor_run": "執行動作",
    "executor_load_file": "載入 JSON 檔案",
    "executor_run_file": "執行檔案",
    "executor_load_dir": "載入目錄",
    "executor_run_dir": "執行所有檔案",
    "executor_output": "輸出:",
    "executor_file_path": "檔案路徑:",
    "executor_dir_path": "目錄路徑:",
    # Reports tab
    "report_file_name": "報告檔案名稱:",
    "report_file_name_default": "test_report",
    "report_generate_html": "產生 HTML 報告",
    "report_generate_json": "產生 JSON 報告",
    "report_generate_xml": "產生 XML 報告",
    "report_status": "報告狀態:",
    # Mock Server tab
    "mock_host": "主機:",
    "mock_port": "埠號:",
    "mock_start": "啟動伺服器",
    "mock_status": "伺服器狀態:",
    "mock_status_stopped": "已停止",
    "mock_status_running": "運行中",
    # Test Records tab
    "records_success": "成功紀錄:",
    "records_error": "錯誤紀錄:",
    "records_clean": "清除所有紀錄",
    "records_refresh": "重新整理",
    "records_count": "成功: {success} | 錯誤: {error}",
    # Tools tab
    "tools_json_reformat": "JSON 格式化",
    "tools_json_input": "JSON 輸入:",
    "tools_json_output": "格式化輸出:",
    "tools_json_format_btn": "格式化",
    "tools_json_read": "讀取 JSON 檔案",
    "tools_json_write": "寫入 JSON 檔案",
    "tools_xml_reformat": "XML 格式化",
    "tools_xml_input": "XML 檔案路徑:",
    "tools_xml_reformat_btn": "格式化 XML",
    "tools_create_project": "建立專案",
    "tools_project_path": "專案路徑:",
    "tools_project_name": "專案名稱:",
    "tools_project_create_btn": "建立",
    "tools_project_name_default": "APITestka",
    # Common
    "browse": "瀏覽...",
    "clear": "清除",
    "success": "成功",
    "error": "錯誤",
}
